o=RootPathJT(thisProcess.nowExecutingPath.dirname++"/presets4/");

o.dir.entries
o.dir.namesEntries
o.dir.namesEntriesWithoutNumbers
o.dir.namesEntriesWithoutNumbersWithoutExtensions

o.entries
o.namesEntries
o.namesEntriesWithoutNumbers
o.namesEntriesWithoutNumbersWithoutExtensions

o.arrayOfPathJTs
o.arrayOfPathJTs.do{|o| o.path.postln}


//--------------------------------------------------------------------------------------------------------------
o=RootPathJT(thisProcess.nowExecutingPath.dirname++"/presets5/");
o.dir
//--------------------------------------------------------------------------------------------------------------