( '_curveReleasefunc': "nil", 'releaseTime': 0.0, 'loop': 1.0, 'rate': [ 0.5, 2.0 ], 
  'durRateScale': -1.0, '_startFramefunc': "nil", 'curveRelease': -4.0, 'azimuth': [ -1.0, 1.0 ], '_durfunc': "nil", 
  '_reversefunc': "nil", 'attackTime': 0.0, '_durRateScalefunc': "nil", 'reverse': 0.0, 'delayTime': [ 0.0, 1.0 ], 
  '_attackTimefunc': "nil", '_loopfunc': "nil", '_delayTimefunc': "{arg x, p; rrand(x[0],x[1])}", 'dur': -1.0, '_voicesfunc': "nil", 
  '_azimuthfunc': "{arg x, p; rrand(x[0],x[1])}", 'startFrame': 0.0, 'curveAttack': 0.0, '_syncfunc': "nil", 'sync': 0.0, 
  '_curveAttackfunc': "nil", 'voices': 62.0, '_ratefunc': "{arg x, p; exprand(x[0],x[1])}", '_releaseTimefunc': "nil", '_ampRateScalefunc': "nil", 
  'ampRateScale': 0.0 )