( '_loopfunc': "nil", '_voicesfunc': "nil", '_startFramefunc': "nil", 'sync': 0.0, 
  'voices': 125.0, 'curveRelease': -4.0, '_syncfunc': "nil", '_ratefunc': "{arg x, p; exprand(x[0],x[1])}", '_durRateScalefunc': "nil", 
  'startFrame': 0.0, 'attackTime': 0.0, '_attackTimefunc': "nil", '_releaseTimefunc': "nil", 'delayTime': [ 0.0, 0.02631530624391 ], 
  '_curveReleasefunc': "nil", 'releaseTime': 1.0, 'durRateScale': -1.0, '_delayTimefunc': "{arg x, p; rrand(x[0],x[1])}", 'ampRateScale': 0.0, 
  '_durfunc': "nil", 'reverse': 0.0, '_azimuthfunc': "{arg x, p; rrand(x[0],x[1])}", '_reversefunc': "nil", 'azimuth': [ -1.0, 1.0 ], 
  'dur': -1.0, 'rate': [ 0.19970272526528, 16.628147616509 ], 'loop': 1.0, '_curveAttackfunc': "nil", 'curveAttack': 0.0 )